spring:
  datasource:
    url: jdbc:mysql://umc-5th-fighting-db.ccvc3kglagfx.ap-northeast-2.rds.amazonaws.com:3306/nadlewe
    username: root
    password: mypassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: none
        generate_ddl: true
        default_batch_fetch_size: 1000